trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadGitHubRelease@0
  inputs:
    connection: 'bmatthews-orange'
    userRepository: 'githubtest'
    defaultVersionType: 'latest'
    downloadPath: '$(System.ArtifactsDirectory)'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml